const express = require('express')
const router = express.Router()
const userController = require('../controllers/user')
const auth = require('../middlewares/auth')

router.post('/register',userController.register)
router.get('/verify/:userId',userController.verifyMail)
router.post('/login',userController.login)
router.post('/otpLogin',userController.otpLogin)
router.post('/resetPassword',userController.resetPassword)
router.post('/forgottPassword',userController.forgottPassword)
router.post('/googleLogin',userController.googleLogin)
router.get('/showBikes',auth.verifyUserToken,userController.getBikes)
router.get('/profile',auth.verifyUserToken,userController.loadProfile)
router.patch('/editProfile',auth.verifyUserToken,userController.editProfile)
router.post('/createClub',auth.verifyUserToken,userController.createClub)
router.get('/clubs',auth.verifyUserToken,userController.getClubs)
router.patch('/removeRequest',auth.verifyUserToken,userController.removeRequest)
router.get('/yourClubs',auth.verifyUserToken,userController.getYourClubs)
router.patch('/joinClub',auth.verifyUserToken,userController.joinClub)
router.get('/getSingleBike/:bikeId',auth.verifyUserToken,userController.getSingleBike)
router.post('/addReview',auth.verifyUserToken,userController.addReview)
router.patch('/returnBike',auth.verifyUserToken,userController.returnBike)
router.get('/paymentSuccess',userController.paymentSuccess)
router.get('/paymentFail',userController.paymentFail)
router.get('/getQuestions',auth.verifyUserToken,userController.getQuestions)
router.post('/addQuestion',auth.verifyUserToken,userController.addQuestion)
router.post('/addAnswer',auth.verifyUserToken,userController.addAnswer)
router.post('/addLike',auth.verifyUserToken,userController.addLike)
router.post('/disLike',auth.verifyUserToken,userController.disLike)
router.post('/addBike',auth.verifyUserToken,userController.addBike)
router.post('/editBike',auth.verifyUserToken,userController.editBike)

module.exports = router